apiVersion: apps/v1
kind: Deployment
metadata:
  name: relationships
  namespace: spicedb
  labels:
    app: relationships
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relationships
  template:
    metadata:
      labels:
        app: relationships
    spec:
      containers:
        - name: relationships
          image: quay.io/cloudservices/kessel-relations:latest
          # image: quay.io/redhat-services-prod/project-kessel-tenant/kessel-relations/relations-api:latest
          ports:
            - containerPort: 8000
            - containerPort: 9000
          env:
            - name: SPICEDB_PRESHARED
              valueFrom:
                secretKeyRef:
                  key: preshared_key
                  name: dev-spicedb-config
                  # name: spicedb-config
            - name: SPICEDB_ENDPOINT
              value: spicedb-cr:50051
            - name: SPICEDB_SCHEMA_FILE
              value: /etc/schema/schema.zed
          livenessProbe:
            httpGet:
              path: /api/authz/livez
              port: 8000
          readinessProbe:
            httpGet:
              path: /api/authz/readyz
              port: 8000
          resources:
            limits:
              cpu: 300m
              memory: 1Gi
            requests:
              cpu: 150m
              memory: 512Mi
          volumeMounts:
          - mountPath: /etc/schema
            name: schema
          # - mountPath: /config
          #   name: relations-api-config
      volumes:
        - configMap:
            name: spicedb-schema
          name: schema
        - configMap:
            name: relations-api-config
          name: relations-api-config
